### ISSUE TITLE
Definition of Gini-Simpson index

### ISSUE THREAD

**Issue by marberts** [schneiderpy/concstats#3]
Hello,

I tried using the `concstats_simpson()` function to calculate the Gini-Simpson index with version 0.1.6 of `concstats`. I was expecting this to be the same as 1 minus the HH index, but that's not the case.

``` r
x <- 1:5
x <- x / sum(x)
all.equal(concstats::concstats_simpson(x), 1 - sum(x^2))
#> [1] "Mean relative difference: 0.06849315"
```

<sup>Created on 2024-01-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The help page for `concstats_simpson()` refers to a [paper by Jost](http://www.loujost.com/Statistics%20and%20Physics/Diversity%20and%20Similarity/JostEntropy%20AndDiversity.pdf) that defines the Gini-Simpson index as 1 - HHI (table 1). The help page also notes that this gets called Gini impurity, Gini's diversity index, the Gibbs-Martin index, and the Blau index; according to the  [Wikipedia page on diversity indexes](https://en.wikipedia.org/wiki/Diversity_index), these are all 1 - HHI.

I think the implementation of `concstats_simpson()` may be incorrect, or perhaps the documentation should be more specific as it doesn't seem to agree with the results of the function. In particular, `concstats_simpson()` calculates a convex combination of 1 and HHI, not 1 - HHI as the documention suggests.

Thanks,
Steve

**Comment by schneiderpy** [comment]
Hi Steve
Thank you for discovering this issue. I have fixed this .. (taking your vector x)
> hhi <- concstats_hhi(x)
[1] 0.2444444
> 1-hhi
[1] 0.7555556
> concstats_simpson(x)
[1] 0.7555556
